EMAIL_USER = "vince.coppens@investialeuven.be"
EMAIL_PASS = "Warrenbuffett1"
SUPABASE_URL = "https://fdnloyofposembrydoif.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbmxveW9mcG9zZW1icnlkb2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTgwMDksImV4cCI6MjA2OTczNDAwOX0.upvUDNm_p5IzNZJvb_gkoUctA23-j7Cfmsqbao1hTNY"